// Five built-in typography theme presets.
// Each theme is a siteStyle fragment: only sets font role and palette fields.
// Applying a theme merges these fields into the current siteStyle — color fields are untouched.

export const TYPOGRAPHY_THEMES = [
  {
    id: "clean",
    name: "Clean",
    description: "Sharp, neutral. Works everywhere.",
    typographyPalette: ["#0f0f0f", "#1a1a1a"],
    fontDisplay: {
      type: "google",
      family: "Inter",
      isVariable: true,
      weightRange: [100, 900],
      colorSlot: 1,
    },
    fontHeading: {
      type: "google",
      family: "Inter",
      isVariable: true,
      weightRange: [100, 900],
      colorSlot: 2,
    },
    fontSubheading: {
      type: "google",
      family: "Inter",
      isVariable: true,
      weightRange: [100, 900],
      colorSlot: 2,
    },
    fontBody: {
      type: "google",
      family: "Inter",
      isVariable: true,
      weightRange: [100, 900],
    },
    fontButton: {
      type: "google",
      family: "Inter",
      isVariable: true,
      weightRange: [100, 900],
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    description:
      "Magazine tension: high-contrast serif display + clean sans body.",
    typographyPalette: ["#0a0a0a", "#1c3d5a"],
    fontDisplay: {
      type: "google",
      family: "Playfair Display",
      isVariable: false,
      weights: [700],
      colorSlot: 1,
    },
    fontHeading: {
      type: "google",
      family: "DM Sans",
      isVariable: true,
      weightRange: [100, 700],
      colorSlot: 2,
    },
    fontSubheading: {
      type: "google",
      family: "DM Sans",
      isVariable: true,
      weightRange: [100, 700],
      colorSlot: 2,
    },
    fontBody: {
      type: "google",
      family: "Lora",
      isVariable: false,
      weights: [400, 600],
    },
    fontButton: {
      type: "google",
      family: "DM Sans",
      isVariable: true,
      weightRange: [100, 700],
    },
  },
  {
    id: "technical",
    name: "Technical",
    description: "Startup energy. Geometric with personality.",
    typographyPalette: ["#09090b", "#3b3b4f"],
    fontDisplay: {
      type: "google",
      family: "Space Grotesk",
      isVariable: true,
      weightRange: [300, 700],
      colorSlot: 1,
    },
    fontHeading: {
      type: "google",
      family: "Space Grotesk",
      isVariable: true,
      weightRange: [300, 700],
      colorSlot: 2,
    },
    fontSubheading: {
      type: "google",
      family: "IBM Plex Sans",
      isVariable: false,
      weights: [400, 500],
      colorSlot: 2,
    },
    fontBody: {
      type: "google",
      family: "IBM Plex Sans",
      isVariable: false,
      weights: [400],
    },
    fontButton: {
      type: "google",
      family: "Space Grotesk",
      isVariable: true,
      weightRange: [300, 700],
    },
  },
  {
    id: "warm",
    name: "Warm",
    description:
      "Approachable and human. Optical-size serif display + rounded sans.",
    typographyPalette: ["#1a0f0a", "#4a3728"],
    fontDisplay: {
      type: "google",
      family: "Fraunces",
      isVariable: true,
      weightRange: [100, 900],
      colorSlot: 1,
    },
    fontHeading: {
      type: "google",
      family: "Nunito",
      isVariable: true,
      weightRange: [200, 900],
      colorSlot: 2,
    },
    fontSubheading: {
      type: "google",
      family: "Nunito",
      isVariable: true,
      weightRange: [200, 900],
      colorSlot: 2,
    },
    fontBody: {
      type: "google",
      family: "Nunito",
      isVariable: true,
      weightRange: [200, 900],
    },
    fontButton: {
      type: "google",
      family: "Nunito",
      isVariable: true,
      weightRange: [200, 900],
    },
  },
  {
    id: "haute",
    name: "Haute",
    description:
      "Fashion/luxury. Ultra-light display, geometric sans, classical body serif.",
    typographyPalette: ["#0d0d0d", "#8b6f47"],
    fontDisplay: {
      type: "google",
      family: "Cormorant Garamond",
      isVariable: false,
      weights: [300, 600],
      colorSlot: 1,
    },
    fontHeading: {
      type: "google",
      family: "Raleway",
      isVariable: true,
      weightRange: [100, 900],
      colorSlot: 2,
    },
    fontSubheading: {
      type: "google",
      family: "Raleway",
      isVariable: true,
      weightRange: [100, 900],
      colorSlot: 2,
    },
    fontBody: {
      type: "google",
      family: "Crimson Pro",
      isVariable: true,
      weightRange: [200, 900],
    },
    fontButton: {
      type: "google",
      family: "Raleway",
      isVariable: true,
      weightRange: [100, 900],
    },
  },
  {
    id: "vintage",
    name: "Vintage",
    description:
      "Old-style serifs with warm character. Evokes print tradition.",
    typographyPalette: ["#2c1810", "#5c3a2e"],
    fontDisplay: {
      type: "google",
      family: "Playfair Display",
      isVariable: true,
      weightRange: [400, 900],
      colorSlot: 1,
    },
    fontHeading: {
      type: "google",
      family: "Cormorant Garamond",
      isVariable: true,
      weightRange: [300, 700],
      colorSlot: 2,
    },
    fontSubheading: {
      type: "google",
      family: "Cormorant Garamond",
      isVariable: true,
      weightRange: [300, 700],
      colorSlot: 2,
    },
    fontBody: {
      type: "google",
      family: "Lora",
      isVariable: true,
      weightRange: [400, 700],
    },
    fontButton: {
      type: "google",
      family: "Playfair Display",
      isVariable: true,
      weightRange: [600, 900],
    },
  },
];
