"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { t } from "@/lib/i18n";
import { SIZE_PRESETS } from "@/lib/imageQuota";
import { writeImageGenerationSnapshot } from "@/lib/adminImageGenerationState";

const SIZE_PRESET_KEYS = [
  "portrait-4-5",
  "square",
  "portrait-3-4",
  "landscape-16-9",
  "story-9-16",
  "a6-150dpi",
];
const SIZE_LABEL_KEYS = {
  "portrait-4-5": "admin.imageSizePortrait45",
  square: "admin.imageSizeSquare",
  "portrait-3-4": "admin.imageSizePortrait34",
  "landscape-16-9": "admin.imageSizeLandscape169",
  "story-9-16": "admin.imageSizeStory916",
  "a6-150dpi": "admin.imageSizeA6",
};

const THUMB_MAX = 160;
function thumbDims(sizeKey) {
  const { width, height } = SIZE_PRESETS[sizeKey] ?? SIZE_PRESETS.square;
  return width >= height
    ? { w: THUMB_MAX, h: Math.round((height / width) * THUMB_MAX) }
    : { w: Math.round((width / height) * THUMB_MAX), h: THUMB_MAX };
}

function formatTimeUntil(isoString) {
  const diff = Math.max(0, new Date(isoString) - Date.now());
  const h = Math.floor(diff / 3600000);
  const m = Math.floor((diff % 3600000) / 60000);
  if (h > 0) return `${h}h ${m}m`;
  return `${m}m`;
}

export default function ImageGenerationPanel({
  description = "",
  initialPrompt,
  onSave,
  context = "editor",
  uploadBackend = "wordpress",
}) {
  const [prompt, setPrompt] = useState(initialPrompt ?? "");
  const [promptLoading, setPromptLoading] = useState(false);
  const [count, setCount] = useState(2);
  const [size, setSize] = useState("portrait-4-5");
  const [generating, setGenerating] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const elapsedRef = useRef(null);
  const [images, setImages] = useState([]);
  const [quota, setQuota] = useState(null);
  const [saving, setSaving] = useState(null);
  const [toast, setToast] = useState(null);
  const hasAutogeneratedPromptRef = useRef(false);

  function showToast(msg, type = "error") {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 4000);
  }

  const persistSnapshot = useCallback((patch) => {
    if (typeof window === "undefined") return;
    const snapshot = writeImageGenerationSnapshot(patch, window.localStorage);
    if (!snapshot) return;
    window.dispatchEvent(
      new CustomEvent("admin:imageSnapshotUpdated", { detail: snapshot }),
    );
  }, []);

  useEffect(() => {
    fetch("/api/admin/generate-image")
      .then((r) => r.json())
      .then((j) => {
        if (j?.ok) setQuota(j.quota);
      })
      .catch(() => {});
  }, []);

  // Clear the elapsed timer if the component unmounts mid-generation
  useEffect(() => {
    return () => clearInterval(elapsedRef.current);
  }, []);

  const generatePrompt = useCallback(async () => {
    if (!description) return;
    setPromptLoading(true);
    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ intent: "image-prompt", description }),
      });
      const json = await res.json();
      if (json?.ok && json?.prompt) setPrompt(json.prompt);
    } catch {
      // leave prompt empty — user types manually
    } finally {
      setPromptLoading(false);
    }
  }, [description]);

  useEffect(() => {
    if (hasAutogeneratedPromptRef.current) return;
    if (initialPrompt) return;
    if (!description) return;
    hasAutogeneratedPromptRef.current = true;
    generatePrompt();
  }, [initialPrompt, description, generatePrompt]);

  async function handleGenerate() {
    if (!prompt.trim() || generating) return;
    const trimmedPrompt = prompt.trim();
    persistSnapshot({
      prompt: trimmedPrompt,
      size,
      count,
      generatedCount: 0,
      status: "running",
    });
    setGenerating(true);
    setElapsed(0);
    setImages([]);
    elapsedRef.current = setInterval(() => setElapsed((s) => s + 1), 1000);
    try {
      const res = await fetch("/api/admin/generate-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: trimmedPrompt, count, size }),
      });
      const json = await res.json();
      if (!res.ok || !json?.ok) {
        if (res.status === 429) {
          if (json?.quota) setQuota(json.quota);
          persistSnapshot({
            prompt: trimmedPrompt,
            size,
            count,
            generatedCount: 0,
            status: "quota",
            requestId: json?.requestId || "",
          });
          const resetTime = json.quota?.resetsAt
            ? new Date(json.quota.resetsAt).toUTCString().slice(17, 22)
            : "?";
          showToast(t("admin.quotaExhausted", { time: resetTime }));
        } else {
          persistSnapshot({
            prompt: trimmedPrompt,
            size,
            count,
            generatedCount: 0,
            status: "error",
            requestId: json?.requestId || "",
          });
          const requestRef = json?.requestId
            ? t("admin.imageErrorRef", { id: json.requestId.slice(0, 8) })
            : "";
          const hint = json?.hint || "";
          const msgParts = [json?.error || t("admin.imageGenFailed"), hint, requestRef]
            .filter(Boolean)
            .join(" ");
          showToast(msgParts);
        }
        return;
      }
      if (json.quota) setQuota(json.quota);
      setImages(json.images || []);
      persistSnapshot({
        prompt: trimmedPrompt,
        size,
        count,
        generatedCount: json.images?.length ?? 0,
        status:
          Array.isArray(json.warnings) && json.warnings.length > 0
            ? "partial"
            : "ok",
        requestId: json?.requestId || "",
      });
      if (Array.isArray(json.warnings) && json.warnings.length > 0) {
        showToast(
          t("admin.imagePartialWarning", { n: json.warnings.length }),
          "info",
        );
      }
      if ((json.images?.length ?? 0) < count) {
        showToast(
          t("admin.imagePartialFail", { n: json.images.length, m: count }),
          "info",
        );
      }
    } catch (err) {
      persistSnapshot({
        prompt: trimmedPrompt,
        size,
        count,
        generatedCount: 0,
        status: "error",
      });
      showToast(err.message || t("admin.imageGenFailed"));
    } finally {
      clearInterval(elapsedRef.current);
      setGenerating(false);
    }
  }

  async function handleSave(dataUrl, idx) {
    if (!onSave) return;
    setSaving(idx);
    try {
      const res = await fetch(dataUrl);
      const blob = await res.blob();
      const form = new FormData();
      form.append(
        "file",
        new File([blob], "ragbaz-ai-image.png", { type: "image/png" }),
      );
      const uploadRes = await fetch(
        `/api/admin/upload?backend=${encodeURIComponent(uploadBackend)}&kind=image`,
        {
          method: "POST",
          body: form,
        },
      );
      const json = await uploadRes.json();
      if (!uploadRes.ok || !json?.ok)
        throw new Error(json?.error || "Upload failed");
      onSave(json.url);
    } catch (err) {
      showToast(err.message || t("admin.imageSaveFailed"));
    } finally {
      setSaving(null);
    }
  }

  function handleDownload(dataUrl, idx) {
    const a = document.createElement("a");
    a.href = dataUrl;
    a.download = `ragbaz-ai-image-${idx + 1}.png`;
    document.body.appendChild(a);
    a.click();
    a.remove();
  }

  const remaining = quota ? Math.max(0, quota.remaining) : null;
  const quotaExhausted = remaining === 0;

  return (
    <div
      className={`border rounded p-4 space-y-3 bg-slate-50 ${context === "chat" ? "text-sm" : ""}`}
    >
      <div className="text-sm font-semibold text-slate-800">
        {t("admin.aiImagesTitle")}
      </div>

      {quota && (
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-xs text-gray-600">
            <div className="flex gap-0.5">
              {Array.from({ length: quota.limit }).map((_, i) => (
                <div
                  key={i}
                  className={`w-3 h-3 rounded-sm ${i < quota.used ? "bg-slate-500" : "bg-gray-200"}`}
                />
              ))}
            </div>
            <span>
              {t("admin.quotaStatus", {
                used: quota.used,
                limit: quota.limit,
                time: formatTimeUntil(quota.resetsAt),
              })}
            </span>
          </div>
          {remaining !== null && remaining <= 2 && remaining > 0 && (
            <p className="text-xs text-amber-700">
              {t("admin.quotaWarning", { n: remaining })}
            </p>
          )}
          {quotaExhausted && (
            <p className="text-xs text-red-700">
              {t("admin.quotaExhausted", {
                time: new Date(quota.resetsAt).toUTCString().slice(17, 22),
              })}
            </p>
          )}
        </div>
      )}

      <div className="flex gap-2 items-start">
        <textarea
          rows={3}
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder={promptLoading ? "…" : t("admin.imagePromptPlaceholder")}
          disabled={promptLoading}
          className="flex-1 border rounded px-3 py-2 text-sm resize-none"
        />
        <div className="flex flex-col gap-1">
          {context === "editor" && (
            <button
              type="button"
              onClick={generatePrompt}
              disabled={promptLoading || !description}
              title={!description ? "No description available" : undefined}
              className="px-2 py-1 rounded border text-xs text-gray-600 hover:bg-gray-50 disabled:opacity-40 whitespace-nowrap"
            >
              {promptLoading ? "…" : t("admin.regeneratePrompt")}
            </button>
          )}
          <button
            type="button"
            onClick={() => {
              navigator.clipboard.writeText(prompt).catch((err) => {
                console.warn(
                  "[ImageGenerationPanel] clipboard write failed:",
                  err,
                );
                showToast(t("admin.copyFailed"));
              });
            }}
            disabled={!prompt.trim()}
            className="px-2 py-1 rounded border text-xs text-gray-600 hover:bg-gray-50 disabled:opacity-40 whitespace-nowrap"
          >
            {t("admin.copyPrompt")}
          </button>
        </div>
      </div>

      <div className="flex flex-wrap gap-3 items-end">
        <div className="flex flex-col gap-1">
          <span className="text-xs text-gray-500">{t("admin.imageCount")}</span>
          <div className="flex gap-1">
            {[1, 2, 3].map((n) => (
              <button
                key={n}
                type="button"
                onClick={() => setCount(n)}
                className={`px-3 py-1 rounded border text-sm ${
                  count === n
                    ? "bg-slate-600 text-white border-slate-600"
                    : "hover:bg-gray-50"
                }`}
              >
                {n}
              </button>
            ))}
          </div>
        </div>

        <div className="flex flex-col gap-1">
          <span
            className="text-xs text-gray-500"
            title={t("admin.imageSizeNeuronTip")}
          >
            {t("admin.imageSize")} ⓘ
          </span>
          <select
            value={size}
            onChange={(e) => setSize(e.target.value)}
            className="border rounded px-2 py-1 text-sm"
          >
            {SIZE_PRESET_KEYS.map((key) => (
              <option key={key} value={key}>
                {t(SIZE_LABEL_KEYS[key])}
              </option>
            ))}
          </select>
        </div>

        <button
          type="button"
          onClick={handleGenerate}
          disabled={generating || quotaExhausted || !prompt.trim()}
          className="px-4 py-2 rounded bg-slate-600 text-white hover:bg-slate-700 disabled:opacity-50 text-sm ml-auto"
        >
          {generating ? `${elapsed}s…` : t("admin.generateButton")}
        </button>
      </div>

      {toast && (
        <div
          className={`text-xs px-3 py-2 rounded ${toast.type === "info" ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}
        >
          {toast.msg}
        </div>
      )}

      {images.length > 0 && (
        <div className="flex flex-wrap gap-3">
          {images.map((img, idx) => {
            const { w, h } = thumbDims(size);
            return (
              <div key={idx} className="flex flex-col gap-1">
                <img
                  src={img}
                  alt={`Generated ${idx + 1}`}
                  className="rounded border object-cover"
                  style={{ width: w, height: h }}
                />
                <div className="flex gap-1">
                  {onSave && (
                    <button
                      type="button"
                      onClick={() => handleSave(img, idx)}
                      disabled={saving !== null}
                      className="flex-1 px-2 py-1 rounded border text-xs hover:bg-gray-50 disabled:opacity-50"
                    >
                      {saving === idx ? "…" : t("admin.saveImage")}
                    </button>
                  )}
                  <button
                    type="button"
                    onClick={() => handleDownload(img, idx)}
                    className="flex-1 px-2 py-1 rounded border text-xs hover:bg-gray-50"
                  >
                    {t("admin.downloadImage")}
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
