import { Montserrat, Nunito } from "next/font/google";
import "./globals.css";

// Note: You can use nested layouts too in Next.js - https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#per-page-layouts
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["600", "900"],
  style: ["normal", "italic"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["600", "700"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${nunito.variable} antialiased`}>
        <main className="bg-stone-100 text-gray-800 min-h-screen">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
